apiVersion: apps/v1
kind: Deployment
metadata:
  name: qslog-back
  labels:
    app: qslog-back
spec:
  selector:
    matchLabels:
      app: qslog-back
  replicas: 1
  template:
    metadata:
      labels:
        app: qslog-back
    spec:
      containers:
      - name: qslog-back
        image: danilodumba/qslog-back:1.5.3
        ports:
        - containerPort:  80
        env:
        - name: MongoConnection__ConnectionString
          valueFrom:
            secretKeyRef:
              name: qslog
              key: mongoDB
        - name: QsLogSettings__RabbitConnection
          valueFrom:
            secretKeyRef:
              name: qslog
              key: habbitMQ
        - name: SecurityKey
          valueFrom:
            secretKeyRef:
              name: qslog
              key: SecurityKey
   