name: Docker Image API CI

on:
  push:
    branches: [ "master" ]

jobs:
  CI-Docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3    
    - name: Docker Login
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image 
      run: docker build . --file qslog-back/Dockerfile --tag danilodumba/qslog-back:1.5.3
    - name: Build the Docker image latest 
      run: docker build . --file qslog-back/Dockerfile --tag danilodumba/qslog-back
    - name: Docker Push
      run: | 
        docker push danilodumba/qslog-back:1.5.3
        docker push danilodumba/qslog-back
